### ISSUE TITLE
Can't upgrade to Drupal 7.37 using packagist.drupal-composer.org

### ISSUE THREAD

**Issue by adrenth-mixcom** [drupal-composer/drupal-packagist#32]
Hi guys,

I'd like to update our Drupal Composer projects to the new Drupal Core (version 7.37). This version shows up at the packagist detail page: https://packagist.drupal-composer.org/packages/drupal/drupal, but it's not installing.

Fragments from composer.json:

```
  ...
  "repositories": [
    {
      "type": "composer",
      "url": "http://packagist.drupal-composer.org/"
    }
  ],
  "require": {
    "drupal/drupal": "7.*",
    ...
  },
  ...
  "minimum-stability": "dev",
  "prefer-stable": true
```

When doing a `composer show drupal/drupal`, version 7.37.0 doesn't show up.
I've already cleared composer's cache.

```
$ composer show drupal/drupal
name     : drupal/drupal
descrip. : Handles general site configuration for administrators.
keywords :
versions : 9.x-dev, 8.1.x-dev, 8.0.x-dev, 8.0.0, 8.0.0-beta10, 8.0.0-beta9, 8.0.0-beta8, 8.0.0-beta7, 8.0.0-beta6, 8.0.0-beta5, 8.0.0-beta4, 8.0.0-beta3, 8.0.0-beta2, 8.0.0-beta1, 8.0.0-alpha15, 8.0.0-alpha14, 8.0-alpha13, 8.0-alpha12, 8.0-alpha11, 8.0-alpha10, 8.0-alpha9, 8.0-alpha8, 8.0-alpha7, 8.0-alpha6, 8.0-alpha5, 8.0-alpha4, 8.0-alpha3, 8.0-alpha2, 8.0-alpha1, 7.x-dev, 7.36.0, 7.35.0, 7.34.0, 7.33.0, 7.32.0, 7.31.0, 7.30.0, 7.29.0, 7.28.0, 7.27.0, 7.26.0, 7.25.0, 7.24.0, 7.23.0, 7.22.0, 7.21.0, 7.20.0, 7.19.0, 7.18.0, 7.17.0, 7.16.0, 7.15.0, 7.14.0, 7.13.0, 7.12.0, 7.11.0, 7.10.0, 7.9.0, 7.8.0, 7.7.0, 7.6.0, 7.5.0, 7.4.0, 7.3.0, 7.2.0, 7.1.0, 7.0.0
type     : drupal-core
license  :
source   : [git] http://git.drupal.org/project/drupal d06d55ce134ed177a2e19f726e30f3eb350f0695
dist     : [zip] http://ftp.drupal.org/files/projects/drupal-9.x-dev.zip
names    : drupal/drupal, drupal/action, drupal/aggregator, drupal/ban, drupal/block, drupal/book, drupal/breakpoint, drupal/color, drupal/comment, drupal/config, drupal/contact, drupal/contextual, drupal/dblog, drupal/field, drupal/email, drupal/field_sql_storage, drupal/link, drupal/number, drupal/options, drupal/text, drupal/field_ui, drupal/file, drupal/filter, drupal/forum, drupal/help, drupal/history, drupal/image, drupal/jsonld, drupal/language, drupal/layout, drupal/locale, drupal/menu, drupal/node, drupal/openid, drupal/overlay, drupal/path, drupal/php, drupal/picture, drupal/poll, drupal/rdf, drupal/rest, drupal/search, drupal/shortcut, drupal/statistics, drupal/syslog, drupal/system, drupal/taxonomy, drupal/toolbar, drupal/tracker, drupal/translation, drupal/translation_entity, drupal/update, drupal/user, drupal/views, drupal/views_ui, drupal/xmlrpc, drupal/minimal, drupal/standard, drupal/bartik, drupal/seven, drupal/stark
```

**Comment by webflo** [comment]
Sorry the was a permission problem on the server because i rebuild the package index with the wrong user a few days ago. I should have caught this earlier. The bug is fixed now. Please test again.

Btw, you could use **https://**packagist.drupal-composer.org/ because this is our new default domain.

**Comment by adrenth-mixcom** [comment]
At first got this exception from composer (while doing a `composer update`): 

```
[Composer\Repository\RepositorySecurityException]                                                                                                                                             
  The contents of http://packagist.drupal-composer.org/p/drupal/drupal$f4de725e0ec19547d5791f6724950020e9b42aae9c215773c4419f1d6ee99df8.json do not match its signature. This should indicate   
  a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.   
```

Got rid of it by removing the composer.lock file to start from a clean slate. But still no luck.
The output shows the latest Drupal 7 core version now (7.37.0).

Any suggestions what to do?

**Comment by webflo** [comment]
Try to run composer clear-cache once before composer update.

**Comment by adrenth-mixcom** [comment]
Cleared the cache, but i'm getting some different 404 responses. Is the package import still running?

Like:

```
[Composer\Downloader\TransportException]                                                                                                                                                      
  The "https://packagist.drupal-composer.org/p/drupal/migrate_d2d_example$effd4fcc4419bfa92c112d39675b01e1c5acfcdf60c4cfd8c754bf3edce897e7.json" file could not be downloaded (HTTP/1.1 404 No  
  t Found)
```

```
[Composer\Downloader\TransportException]                                                                                                                                                      
  The "https://packagist.drupal-composer.org/p/drupal/migrate_extras_profile2$cbf8ccf1d1bf55d1287f527008ecd70abaf4275b3833abcc9f46d232798c7b6e.json" file could not be downloaded (HTTP/1.1 40  
  4 Not Found) 
```

**Comment by webflo** [comment]
migrate_d2d_example is a submodule of migrate_d2d. migrate_d2d_example itself is not in the packagist repo. you can workaround this issue by requiring migrate_d2d in your composer.json

**Comment by adrenth-mixcom** [comment]
This really was a nasty one. 

A composer clear-cache was not enough. Removing the complete cache-path `~/.composer/cache` did the trick eventually. I'm running Drupal 7.37 now. And using the new packagist https URL.

Composer really was confused after changing the packagist URL, complaining about missing packages and .json files that could not be found.

My solution so far: `sudo rm -rf ~/.composer/cache`.

Many thanks for fixing it and help with solving the issue! Much appreciated!

**Comment by webflo** [comment]
Great, i hope other users won´t have these problems.
